language: python

services:
  - couchdb

python:
  - 2.7
  - 3.3
  - 3.4
  - pypy

notifications:
  email:
    recipients:
      - rinat.sabitov@gmail.com
    on_success: change
    on_failure: change

install:
  - pip install coverage mock requests nose responses coveralls

script:
  - nosetests -vv --with-coverage --cover-erase --cover-package=pycouchdb --with-doctest

after_success:
    - coveralls
