language: python

services:
- couchdb

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
  - pypy3

notifications:
  email:
    recipients:
      - rinat.sabitov@gmail.com
    on_success: change
    on_failure: change

install:
  - pip install -U pip
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]];
    then pip install "coverage<4"; else
    pip install coverage;
    fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; 
    then pip install unittest2; 
    fi
  - pip install mock requests nose responses coveralls

script:
  - nosetests -vv --with-coverage --cover-erase --cover-package=pycouchdb --with-doctest

after_success:
    - coveralls
